### ISSUE TITLE
Not working for me on Windows 8.1

### ISSUE THREAD

**Issue by m0ngr31** [ExplodingCabbage/sublime-gitignorer#13]
I've used this package on Linux, but on my Windows box it doesn't seem to work correctly. Here's the error I get from the console:

```
reloading plugin Gitignored File Excluder.gitignore_plugin
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "gitignore_plugin in C:\Users\Joe\AppData\Roaming\Sublime Text 3\Installed Packages\Gitignored File Excluder.sublime-package", line 229, in <module>
  File "gitignore_plugin in C:\Users\Joe\AppData\Roaming\Sublime Text 3\Installed Packages\Gitignored File Excluder.sublime-package", line 35, in start
  File "gitignore_plugin in C:\Users\Joe\AppData\Roaming\Sublime Text 3\Installed Packages\Gitignored File Excluder.sublime-package", line 32, in run
  File "gitignore_plugin in C:\Users\Joe\AppData\Roaming\Sublime Text 3\Installed Packages\Gitignored File Excluder.sublime-package", line 48, in update_file_exclude_patterns
  File "gitignore_plugin in C:\Users\Joe\AppData\Roaming\Sublime Text 3\Installed Packages\Gitignored File Excluder.sublime-package", line 89, in all_ignored_paths
  File "gitignore_plugin in C:\Users\Joe\AppData\Roaming\Sublime Text 3\Installed Packages\Gitignored File Excluder.sublime-package", line 110, in folder_ignored_paths
  File "gitignore_plugin in C:\Users\Joe\AppData\Roaming\Sublime Text 3\Installed Packages\Gitignored File Excluder.sublime-package", line 130, in is_in_git_repo
  File "./subprocess.py", line 523, in call
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by towertop** [comment]
Same error on Windows 10 and Sublime Text 3.
