### ISSUE TITLE
Error on Linux when opening Sublime 

### ISSUE THREAD

**Issue by doubleloop** [ExplodingCabbage/sublime-gitignorer#15]
After installation it worked until sublime restart. Now I get error: 
```
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text_3/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "gitignore_plugin in /home/doubleloop/.config/sublime-text-3/Installed Packages/Gitignored File Excluder.sublime-package", line 229, in <module>
  File "gitignore_plugin in /home/doubleloop/.config/sublime-text-3/Installed Packages/Gitignored File Excluder.sublime-package", line 35, in start
  File "gitignore_plugin in /home/doubleloop/.config/sublime-text-3/Installed Packages/Gitignored File Excluder.sublime-package", line 32, in run
  File "gitignore_plugin in /home/doubleloop/.config/sublime-text-3/Installed Packages/Gitignored File Excluder.sublime-package", line 65, in update_file_exclude_patterns
TypeError: 'NoneType' object is not iterable
```

**Comment by ExplodingCabbage** [comment]
Thanks for the traceback - this is *much* more useful than the report in issue https://github.com/ExplodingCabbage/sublime-gitignorer/issues/8, and might well even be the same bug. I'll look when I have a chance.

**Comment by Sewdn** [comment]
I have the same issue.
Ubuntu 14.04.1 LTS
Sublime Text Build 3083

**Comment by ocolot** [comment]
Same issue here on macOS 10.12.6 with Sublime Text build 3143

**Comment by ricab** [comment]
Same here, ubuntu 16.04, sublime 3176
