### ISSUE TITLE
TypeError in update_file_exclude_patterns()

### ISSUE THREAD

**Issue by y0ssar1an** [ExplodingCabbage/sublime-gitignorer#18]
The plugin is completely broken for me.

My system:
OS X 10.10.5
Sublime Text 3 build 3095
Installed through Package Control

Here's the traceback from the console:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "gitignore_plugin in /Users/ryan/Library/Application Support/Sublime Text 3/Installed Packages/Gitignored File Excluder.sublime-package", line 229, in <module>
  File "gitignore_plugin in /Users/ryan/Library/Application Support/Sublime Text 3/Installed Packages/Gitignored File Excluder.sublime-package", line 35, in start
  File "gitignore_plugin in /Users/ryan/Library/Application Support/Sublime Text 3/Installed Packages/Gitignored File Excluder.sublime-package", line 32, in run
  File "gitignore_plugin in /Users/ryan/Library/Application Support/Sublime Text 3/Installed Packages/Gitignored File Excluder.sublime-package", line 65, in update_file_exclude_patterns
TypeError: 'NoneType' object is not iterable
```

**Comment by piersadrian** [comment]
Same error here.

OS X 10.11.1
ST3 stable, b3083
Package Control installation

Same stack trace as above.

**Comment by tschofen** [comment]
Similar error here.
```
reloading plugin Gitignored File Excluder.gitignore_plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "gitignore_plugin in /Users/34787/Library/Application Support/Sublime Text 3/Installed Packages/Gitignored File Excluder.sublime-package", line 229, in <module>
  File "gitignore_plugin in /Users/34787/Library/Application Support/Sublime Text 3/Installed Packages/Gitignored File Excluder.sublime-package", line 35, in start
  File "gitignore_plugin in /Users/34787/Library/Application Support/Sublime Text 3/Installed Packages/Gitignored File Excluder.sublime-package", line 32, in run
  File "gitignore_plugin in /Users/34787/Library/Application Support/Sublime Text 3/Installed Packages/Gitignored File Excluder.sublime-package", line 65, in update_file_exclude_patterns
TypeError: 'NoneType' object is not iterable
```

OS X 10.12.4
ST3 stabel, 3126
Package Control installation
