### ISSUE TITLE
Doesn't work on Mac OX X 10.10.1

### ISSUE THREAD

**Issue by chrisyip** [ExplodingCabbage/sublime-gitignorer#8]
![screen shot 2014-12-28 at 5 01 56 pm](https://cloud.githubusercontent.com/assets/189559/5563504/8d526b00-8eb3-11e4-8838-bdff5dce4a65.png)

Here's my updated settings:

``` json
{
  "extra_file_exclude_patterns":
  [
    "*.pyc",
    "*.pyo",
    "*.exe",
    "*.dll",
    "*.obj",
    "*.o",
    "*.a",
    "*.lib",
    "*.so",
    "*.dylib",
    "*.ncb",
    "*.sdf",
    "*.suo",
    "*.pdb",
    "*.idb",
    ".DS_Store",
    "*.class",
    "*.psd",
    "*.db",
    "*.sublime-workspace"
  ],
  "extra_folder_exclude_patterns":
  [
    ".idea",
    ".svn",
    ".git",
    ".hg",
    "CVS",
    ".codekit-cache",
    "node_modules",
    "tmp",
    ".file-cache",
  ],
  "folder_exclude_patterns":
  [
    ".idea",
    ".svn",
    ".git",
    ".hg",
    "CVS",
    ".codekit-cache",
    "node_modules",
    "tmp",
    ".file-cache"
  ]
}
```

Sublime Text 3066 on OX X 10.10.1

**Comment by wkirby** [comment]
Same — not working on 10.10.2.

**Comment by utkarsh2012** [comment]
Any update on this? This doesn't work anymore.

**Comment by ExplodingCabbage** [comment]
I don't own a Mac, but I use one at work now, and will look into this tonight before I leave if I get the chance. If I can't reproduce I'll stick a "help wanted" label on here.

**Comment by ExplodingCabbage** [comment]
Sorry for the delay. Just updated to OS X 10.10.3 and I can't reproduce this. If anybody is still able to reproduce it, could you provide some more information that could help me identify the issue, like a sample project or any output you see in the <kbd>CTRL</kbd>-<kbd>C</kbd> console in Sublime while the plugin is failing?

**Comment by dwahyudi** [comment]
I think you might just need to reinstall this plugin.
Sometimes, the plugin will just work after you committed the .gitignore file.

I did it too. It was failed at first, but after reinstalled the plugin, it works.

**Comment by chrisyip** [comment]
@dwahyudi wired, I tried reinstall before, didn't work. But now, it works. Thanks.

**Comment by kolis** [comment]
I'm getting this exception
```
reloading plugin Gitignored File Excluder.gitignore_plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "gitignore_plugin in /Users/nils/Library/Application Support/Sublime Text 3/Installed Packages/Gitignored File Excluder.sublime-package", line 229, in <module>
  File "gitignore_plugin in /Users/nils/Library/Application Support/Sublime Text 3/Installed Packages/Gitignored File Excluder.sublime-package", line 35, in start
  File "gitignore_plugin in /Users/nils/Library/Application Support/Sublime Text 3/Installed Packages/Gitignored File Excluder.sublime-package", line 32, in run
  File "gitignore_plugin in /Users/nils/Library/Application Support/Sublime Text 3/Installed Packages/Gitignored File Excluder.sublime-package", line 65, in update_file_exclude_patterns
TypeError: 'NoneType' object is not iterable
```

**Comment by aericson** [comment]
In case anyone runs into this.

Fix permission of Sublime Text folder as explained here: https://github.com/SublimeTextIssues/Core/issues/1021#issuecomment-365011418

then reinstall this package, restart sublime, reinstall this package. Worked for me.
